name: Terraform Apply

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Initialise project and view terraform plan
        run: |
          cd terraform
          terraform fmt
          terraform init -input=false
      - name: Validate terraform plan
        run: |
          cd terraform
          terraform validate
      - name: plan
        run: |
          cd terraform
          terraform plan -input=false -compact-warnings -out=plan.file -no-color